<?php 
echo nl2br("Ferruccio Lamborghini vergaarde zijn fortuin voornamelijk in de tractorenfabricage in Italië en Spanje. Hij was begin jaren zestig een bon vivant met een passie voor snelle wagens en bezat daarvan een aanzienlijke collectie. Lamborghini had onder andere een splinternieuwe Ferrari die in één jaar tijd viermaal terug naar de fabriek moest wegens gebreken. Toen Ferrucio de twintig jaar oudere Enzo Ferrari hierover misnoegd aansprak (de twee woonden slechts veertig kilometer van elkaar) gaat het verhaal dat deze laatste hem neerbuigend afwimpelde met;\"Ga je maar weer met je tractoren bezighouden en laat het bouwen van sportwagens over aan hen die er verstand van hebben\"

Enzo Ferrari wist niet wat hem overkwam toen drie maanden later op de jaarlijkse autosalon van Genève van 1963 een prototype van een nieuwe supersportwagen de show stal: de Lamborghini 350 GTV, gesierd met een radiatorembleem van een aanvallende stier (het logo van de tractorenbouwer), die zich de komende veertig jaar fel zou weten te meten met het steigerende Ferrari-paard.

Ferruccio Lamborghini was geslaagd in een onwaarschijnlijke krachttoer: in minder dan drie maanden een team van ingenieurs, stylisten en carrosseriebouwers aan te werven in zijn tractorenbouwbedrijf met als enige opdracht: \"Bouw mij een sportwagen die in elk opzicht superieur is aan Ferrari\". Van meet af aan werd het nieuwe automerk een sensatie, met haar technologie die verder was (onafhankelijke ophanging, dwarsliggende middenmotor, aerodynamica...) dan die van de - eerder conservatieve - Ferrari's. Lamborghini richtte zich echter puur op de verkoop van straatmodellen aan particulieren en liet het racen aan anderen over. Hoewel Ferrari al ruim een halve eeuw de F1– en F2-klassementen zou blijven domineren zou het merk sinds 1964 wel degelijk onafgebroken de hete adem van Lamborghini in zijn nek blijven voelen, tijdens de jaren die daarop volgden.

De laatste decennia - nadat Ferruccio Lamborghini zijn bedrijf verkocht - vormde Lamborghini een onderdeel van verscheidene autofabrikanten, waaronder Chrysler en het Indonesische MegaTech (van Soeharto's zoon Tommy). In 1998 is het bedrijf in zijn geheel overgenomen door Audi. Sinds het bedrijf door deze Duitse Volkswagen-dochter werd overgenomen, steeg het aantal werknemers van 300 tot 450.
"); ?>
